WebApplicationAdo/Models/Times.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplicationAdo.Models
{
    public class Times
    {
        [Display(Name = "Id")]
        public int TimeId { get; set; }

        [Required(ErrorMessage = "Informe o nome do time")]
        public string Time { get; set; }

        [Required(ErrorMessage = "Informe o estado do time")]
        public string Estado { get; set; }

        [Required(ErrorMessage = "Informe as cores do time")]
        public string Cores { get; set; }
    }
}

WebApplicationAdo/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplicationAdo.Repositorio;

namespace WebApplicationAdo.Controllers
{
    public class LoginController : Controller
    {
        TimeRepositorio _repositorio;

        public LoginController()
        {
            _repositorio = new TimeRepositorio();
        }

        //// GET: Login
        public ActionResult Index()
        {
            return View();
        }

        //// POST: Login
        [HttpPost]

        public ActionResult Entrar(FormCollection collection)
        {
            var usuarioLogado = _repositorio.ObterTimes(collection.Get("email"), collection.Get("senha"));
            if (usuarioLogado != null)
            {
                Session["usuarioLogado"] = usuarioLogado;
                return Redirect("/");
            }

            TempData["erro"] = "Verifique seu E-mail e Senha.";
            return Redirect("/Login");
        }
    }
}

WebApplicationAdo/Controllers/TimeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplicationAdo.Models;
using WebApplicationAdo.Repositorio;

namespace WebApplicationAdo.Controllers
{
    public class TimeController : Controller
    {
        private  TimeRepositorio _repositorio;
        
        public ActionResult ObterTimes()
        {
            _repositorio = new TimeRepositorio();
            var times = _repositorio.ObterTimes();
            ModelState.Clear();
            return View(times);
        }

        [HttpGet]
        public ActionResult IncluirTime()
        {
            return View(new Times());
        }

        [HttpPost]
        public ActionResult IncluirTime(Times timeObj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _repositorio = new TimeRepositorio();

                    if (_repositorio.AdicionarTime(timeObj))
                    {
                        ViewBag.Mensagem = "Time cadastrado com sucesso";
                    }
                }

                return View();
            }
            catch (Exception)
            {
                return View("ObterTimes");
            }
        }

        [HttpGet]
        public ActionResult EditarTime(int id)
        {
            _repositorio = new TimeRepositorio();
            var time = _repositorio.ObterTimes().Find(t => t.TimeId == id); //Não é uma boa prática, crie uma proc que retorne somente 1 time
            return View(time);
        }

        [HttpPost]
        public ActionResult EditarTime(Times timeObj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _repositorio = new TimeRepositorio();
                    _repositorio.AtualizarTime(timeObj);
                }

                return RedirectToAction("ObterTimes");
            }
            catch (Exception)
            {
                return View("ObterTimes");
            }
        }
        
        public ActionResult ExcluirTime(int id)
        {
            try
            {
                _repositorio = new TimeRepositorio();
                if (_repositorio.ExcluirTime(id))
                {
                    ViewBag.Mensagem = "Time excluído com sucesso";
                }

                return RedirectToAction("ObterTimes");

            }
            catch (Exception)
            {
                return View("ObterTimes");
            }
        }
    }
}

WebApplicationAdo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Times de Futebol</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Times de Futebol", "ObterTimes", "Time", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year -  <a href="http://www.aprendadotnet.com.br" target="_blank">Aprenda DotNet</a>  </p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>

WebApplicationAdo/Views/Time/EditarTime.cshtml
@model WebApplicationAdo.Models.Times

@{
    ViewBag.Title = "EditarTime";
}

<h2>Alterar Time</h2>

<div>
    @Html.ActionLink("Listar todos os times", "ObterTimes")
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Times</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TimeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimeId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cores, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cores, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cores, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
        
        @ViewBag.Mensagem
    </div>
}

WebApplicationAdo/Views/Time/IncluirTime.cshtml
@model WebApplicationAdo.Models.Times

@{
    ViewBag.Title = "IncluirTime";
}

<h2>Cadastrar time</h2>


<div>

    @Html.ActionLink("Listar todos os times", "ObterTimes")

</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cores, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cores, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cores, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>

        @ViewBag.Mensagem
    </div>
}

WebApplicationAdo/Views/Time/ObterTimes.cshtml
@model IEnumerable<WebApplicationAdo.Models.Times>

@{
    ViewBag.Title = "ObterTimes";
}

<h2>MVC 5 COM ADO</h2>

<p>
    @Html.ActionLink("Criar novo time", "IncluirTime")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TimeId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cores)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TimeId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Time)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cores)
        </td>
        <td>
            @Html.ActionLink("Editar", "EditarTime", new { id=item.TimeId }) |
            @Html.ActionLink("Excluir", "ExcluirTime", new { id = item.TimeId }, new { onclick = "return confirm('Tem certeza que deseja excluir?');" })
        </td>
    </tr>
}

</table>